steps:
- name: 'gcr.io/cloud-builders/docker'
  id: Build
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/skaffold-test:$BUILD_ID', '.']
- name: 'gcr.io/cloud-builders/docker'
  id: Push to Google Container Registry
  args: ['push', 'gcr.io/$PROJECT_ID/skaffold-test:$BUILD_ID']
- name: gcr.io/$PROJECT_ID/crane
  id: Retrieve the image digest
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - 'echo gcr.io/$PROJECT_ID/skaffold-test@$(crane digest gcr.io/$PROJECT_ID/skaffold-test:$BUILD_ID) > /workspace/image_name'
- name: 'gcr.io/cloud-builders/kubectl'
  id: Update Kubernetes deployment
  entrypoint: '/bin/sh'
  args:
  - '-c'
  - '/builder/kubectl.bash set image deployment/hello-world hello-world=$(cat /workspace/image_name)'
  env:
  - 'CLOUDSDK_COMPUTE_ZONE=us-central1-a'
  - 'CLOUDSDK_CONTAINER_CLUSTER=factorio-cluster'
images:
- 'gcr.io/$PROJECT_ID/skaffold-test:$BUILD_ID'
